# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 22:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170802_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 2, 22, 48, 19, 401504, tzinfo=utc), verbose_name='dia_creado'),
        ),
    ]
