# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 00:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170802_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2017, 8, 3, 0, 14, 19, 944308, tzinfo=utc), verbose_name='dia_creado')),
            ],
        ),
        migrations.AlterField(
            model_name='personal',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 3, 0, 14, 19, 941166, tzinfo=utc), verbose_name='dia_creado'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='id_personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Personal'),
        ),
    ]
