# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 01:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170802_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesiones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default='ekb7DZe5IqXQgTZXYkQMVmb7hacosm', max_length=30)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2017, 8, 3, 1, 25, 56, 820952, tzinfo=utc), verbose_name='dia_creado')),
                ('fecha_expiracion', models.DateTimeField(default=datetime.datetime(2017, 8, 3, 1, 55, 56, 821127, tzinfo=utc), verbose_name='dia_creado')),
            ],
        ),
        migrations.AddField(
            model_name='personal',
            name='puesto',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personal',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 3, 1, 25, 56, 814228, tzinfo=utc), verbose_name='dia_creado'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 3, 1, 25, 56, 817584, tzinfo=utc), verbose_name='dia_creado'),
        ),
        migrations.AddField(
            model_name='sesiones',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Usuarios'),
        ),
    ]
